# Definir este lado como periférico (recibe órdenes del izquierdo)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Habilitar el soporte para enviar los datos de entrada (mouse/trackball) al lado central
CONFIG_ZMK_SPLIT_PERIPHERAL=y
