# --- OPTIMIZACIONES PARA MACOS ---
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
CONFIG_BT_BUF_ACL_TX_COUNT=32
CONFIG_BT_L2CAP_TX_BUF_COUNT=32

# Fuerza a ZMK a mantener la estabilidad de la conexión con Apple
CONFIG_BT_CTLR_PHY_2M=n

# --- GESTIÓN DE ENERGÍA Y SUEÑO ---
# Tiempo para apagar luces (30 segundos)
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Habilitar deep sleep (Sueño profundo a los 15 minutos para cuidar batería)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# --- ESTABILIDAD BLUETOOTH EXTRA ---
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# --- CONFIGURACIÓN RGB ---
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=280
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50
