manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Vzhao-L
      url-base: https://github.com/Vzhao-L
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-pmw3610-inorichi
      remote: Vzhao-L
      revision: main
      
  self:
    path: config
